### ISSUE TITLE
Character names with hashes (#) are parsed incorrectly

### ISSUE THREAD

**Issue by cantrell** [jonnygreenwald/fountain-js#13]
First, thanks so much maintaining this project. I works very well, and has saved me a ton of time.

I think I found a bug related to CHARACTER NAMES with hashes (#). Specifically, this:

> DISGRUNTLED CITIZEN #⁠1
> (standing)
> Excuse me. How much did it cost?

Gets tokenized like this:

```
{
    "type": "action",
    "text": "DISGRUNTLED CITIZEN #1<br />(standing)<br />Excuse me. How much did it cost?"
}
```

(I've verified with a few different instances.)

Is this an invalid Fountain character name, or a bug? Thanks!

**Comment by jonnygreenwald** [comment]
Thanks for the bug report. 

I'm not sure if hashes and other special characters are allowed in character names regarding the specification or not to be honest. I'll have to look into it and get back to you, but my immediate assumption is that they should be. 

An immediate thought is to try forcing it with an `@` and see if that works or not. The force may be more forgiving. 

I just got out of the woods from a backpacking trip and am traveling back now. I will be back tomorrow and will try to look into this as soon as possible by Monday or Tuesday. 

On Fri, Sep 8, 2023, at 9:12 AM, Christian Cantrell wrote:
> 
> 
> First, thanks so much maintaining this project. I works very well, and has saved me a ton of time.
> 
> I think I found a bug related to CHARACTER NAMES with hashes (#). Specifically, this:
> 
>> 
>> DISGRUNTLED CITIZEN #⁠1
>> (standing)
>> Excuse me. How much did it cost?
>> 
> Gets tokenized like this:
> 
> `{
>     "type": "action",
>     "text": "DISGRUNTLED CITIZEN #1<br />(standing)<br />Excuse me. How much did it cost?"
> }
`

**Comment by cantrell** [comment]
Thanks! I hope you enjoyed the backpacking, and I appreciate the quick response.

**Comment by jonnygreenwald** [comment]
It was very nice, thanks!

I've been reading over the [fountain.io spec](https://fountain.io/syntax/#character) and the details are somewhat scant regarding the interpretation.

> A Character element is any line entirely in uppercase, with one empty line before it and without an empty line after it.
>```
> STEEL
> The man’s a myth!
> ```
> ...
> Character names must include at _least one alphabetical character_. (emphasis mine) “R2D2” works, but “23” does not.

What this tells me is that nothing indicates a special character cannot be used, but to be fair to the original regex writer, it's not specific either. For example, I think you can interpret the "at least one alphabetical character" plus example to mean all names must _start_ with an alphabetical character as the original author of our library did; however, you can also interpret that the specification means anywhere, so something like `1D2` should be valid, since August doesn't say _where_ the alphabetical character should be.

In fact, digging into @nyousefi's [original Regexes](https://github.com/nyousefi/Fountain/blob/master/Fountain/FountainRegexes.m), you can see they don't discriminate that much but confusingly they also seems to allow `23`, which could have been an accident on my part interpreting the [regex](https://regex101.com/r/c3GUPm/1) since I don't do much Objective-C.

So, to dispel that confusion, I jumped into Highland 2, which accepts names like `1D2` but not `23` (except when forced `@`) and also, happily, `DISGRUNTLED CITIZEN #1` works perfectly fine too! 

Given this, I think it's fair to say, you're right and this is a flaw in the original regex.

Here's my [initial attempt at a regex](https://regex101.com/r/5sDwtD/1) that tries to conform to all of the patterns as best I can. It isn't pretty but works as far as I can tell. If it looks good, I'll try this out tomorrow and write some new tests to make sure it doesn't break anything else.

**Comment by cantrell** [comment]
Just updated and tested. Looking good! Thanks!
