### ISSUE TITLE
Action with a newline gets a <br /> inserted

### ISSUE THREAD

**Issue by cantrell** [jonnygreenwald/fountain-js#15]
If you have a line of action with a newline (\n), it gets replaced with a `<br />`.

The problem seems to come from passing `this.tokens` into `to_html()`. If, instead, you make a deep copy (so that `to_html()` doesn't modify the instance), it works as expected. For example:

```
      const tokenCopy = Utils.deepCopy(this.tokens) as Token[];
      return {
        title: titleString,
        html: {
          title_page: tokenCopy
            .filter(token => token.is_title)
            .map(token => this.to_html(token))
            .join(''),
          script: tokenCopy
            .filter(token => !token.is_title)
            .map(token => this.to_html(token))
            .join(''),
        },
        tokens: getTokens ? this.tokens : undefined,
      };
```

**Comment by jonnygreenwald** [comment]
Hi, so I might be misunderstanding, but in the instance of:

```fountain
Murtaugh, springing hell bent for leather -- and folks, 
grab your hats … because just then, a BELL COBRA 
HELICOPTER crests the edge of the bluff.

Screaming, chaos, frenzy.
Three words that apply to this scene.
```

The resulting html output will look as so:

```html
<p>
  Murtaugh, springing hell bent for leather -- and folks, <br />
  grab your hats … because just then, a BELL COBRA <br />
  HELICOPTER crests the edge of the bluff.
</p>
<p>
  Screaming, chaos, frenzy.<br />
  Three words that apply to this scene.
</p>
```

And the `<br />` inserted in-between the lines is unexpected?
_Or_ is there a specific case in which another erroneous `<br />` is inserted where it shouldn't be?

I tried your example with `lodash.clonedeep` since I didn't know where `Utils.deepCopy` was and couldn't find a difference when testing my output with `tokenCopy` versus `this.tokens`.

In case I'm off base, if you could provide an example plus the problematic output, that would be much appreciated in helping direct me.

**Comment by jonnygreenwald** [comment]
_(deleted my earlier comment because I understood what the issue was, sorry for any confusion)_ 🤦‍♀️

It's the `this.inlineLex.reconstruct()`method within `to_html` that's mutating the shallow copy of the token objects. You're right that a deep copy is the way to go and I can fix this with a JSON round-trip; however, it presents some issues that I do want to make you aware of.

I assume you're using the `parse` method to only retrieve the tokens and then are manipulating the tokens to render it into something else other than HTML, thus why having HTML embedded in the token text like `<br />` is causing you issues. But I'm making some big assumptions here, so please correct me if I'm wrong.

The `inlineLex.reconstruct()` method doesn't just work on newlines but is the inline lexer for all inline objects e.g. emphasis, underlines, etc. So what that means is that if I make this change, is that you'll have to perform your own inline lexing to convert these to whatever you want.

For example, given the action:

```fountain
Murtaugh, springing hell bent for leather -- and folks, 
grab your hats … because just then, a _BELL COBRA 
HELICOPTER_ crests the edge of the bluff.
```

Where you want the helicopter name to be underlined, will yield the token:

```javascript
[
  ActionToken {
    type: 'action',
    text: 'Murtaugh, springing hell bent for leather -- and folks, \n' +
      'grab your hats … because just then, a _BELL COBRA \n' +
      'HELICOPTER_ crests the edge of the bluff.'
  }
]
```
^^ e.g. the underline markup is still unchanged since `inlineLex.reconstruct()` didn't mutate the text on the token. Also take note that this doesn't just happen in action but **all tokens**.

So, you'll probably have to run a version of your own inline lexer to solve this issue. I suggest using the code from the [`InlineLexer` class](https://github.com/jonnygreenwald/fountain-js/blob/main/src/lexer.ts) and just replace the html with whatever you want like `<underline>$2</underline>` or whatever, but if you want something more complicated than strings like DOM or something then perhaps this won't work 🤔...

Anyway, thoughts are welcomed here. If this isn't an issue, I can push a fix for this.

**Comment by jonnygreenwald** [comment]
Okay, Pull #16 is up, which will hopefully fix this issue. Let me know if you see any problem with what I've outlined in the request / caveats above. If not, I'll review and merge it.
